# Bank Management System Configuration

[database]
host = "bank-management.mysql.database.azure.com"
user = "Jay1509"
password = "Chotaliya@1509"
name = "Bank"

[application]
name = "Bank Management System"
version = "1.0.0"
description = "A banking system with both console and web interfaces"

[features]
registration = true
deposit = true
withdrawal = true
balance_check = true
money_transfer = true
transaction_tracking = true

[settings]
default_deposit_limit = 100000
default_withdrawal_limit = 50000
session_timeout_minutes = 30

[ui]
theme = "light"
primary_color = "#007bff" 